config/routes.rb
Rails.application.routes.draw do


  #devise_for :members, :controllers=>{:registrations=>'registration'}
  root :to =>'home#index'
  get 'dashboard' => 'home#dashboard'
  get 'cemetoryform' => 'details#new'
  post 'cemetoryform' => 'details#create'
  get 'cemetoryform' => 'details#show'
  get '/list', to: 'details#veiwlist'
  get '/edit', to: 'details#Edit'
  patch '/edit', to: 'details#Update'
  get '/delete', to: 'details#Delete'



  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'

  get 'searchajax',to: 'details#searchajax'
  get 'searchhome',to: 'home#searchhome'

  # get 'adddatamap',to: 'details#adddatamap'


  get 'indexsearch' => 'details#index'
  get 'show' => 'details#show'

  devise_for :members, :controllers => { :omniauth_callbacks => "callbacks" ,:registrations=>'registration'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :details do
      collection { post :search, to: 'details#index' }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heir.rb
class Heir < ApplicationRecord
  belongs_to :member
  validates :name,  presence: true, length: { maximum: 50 }
  validates :address,  presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :heirs, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable,:omniauthable, :authentication_keys => {email: true, login: false} ,
  :omniauth_providers => [:github ,:facebook]

#  attr_accessor :email, :password, :password_confirmation, :remember_me, :username
validates :username,  presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |member|
      member.provider = auth.provider
      member.uid = auth.uid
      member.email = auth.info.email
      puts member.email
      puts "___________________"
      member.password = Devise.friendly_token[0,20]
    end
  end
end

#
#
#
# (43, null, $2a$11$wvLYV5MM6.A3.WL1AMYg0OI7aRydDcvtt8uRlqMWkemsQN6x1XTuu, null, null, null, 1, 2017-01-24 08:55:51.803564, 2017-01-24 08:55:51.803564, ::1, ::1, 2017-01-24 08:55:51.803978, 2017-01-24 08:55:51.803978, null, null, null, null, f, github, 24888013).
# ("email", "encrypted_password", "sign_in_count", "current_sign_in_at", "last_sign_in_at", "current_sign_in_ip", "last_sign_in_ip", "created_at", "updated_at", "provider", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
     added_attrs = [:email,:password,:password_confirmation,:username,:address,:mobaile,:date_of_birth,:is_female,:provider,:uid]
     devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
     devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
     devise_parameter_sanitizer.permit :account_update, keys: added_attrs
   end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

    def github
      @member = Member.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @member
    end

    def facebook
      @member = Member.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @member
    end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_params,:authenticate_member!

  def index

    # @search = Heir.where("member_id=?",current_member.id).search(params[:q]) // for specific memeber login
    @search = Heir.search(params[:q]) #for all member
    @Record = @search.result
    gmap @Record
  end

  def searchajax
    data= params[:data]
    @products=Heir.where('name LIKE ?', "%#{data}%")
    gmap @products
    respond_to do |format|
      format.html
      format.js
   end
  end

  def new
    @heir= Heir.new
  end

  def create
    @heir = Heir.new(heir_params)
    @heir.valid?
    if @heir.errors.blank?
      @heir.save
      redirect_to dashboard_path
    else
      render :action => "new"
    end
  end

  def veiwlist
    @data=Heir.paginate(:per_page => 5, :page => params[:page])
  end

  def show
    redirect_to indexsearch_path
  end

  def Edit
    @heir = Heir.find(params[:id])
  end

  def Update
    @heir = Heir.find(params[:id])
    if @heir.update_attributes(heir_params)
      redirect_to dashboard_path, :id=>@heir
    else
      render 'Edit'
    end
  end

  def Delete
    Heir.find(params[:id]).destroy
    redirect_to list_path
  end

  private

  def gmap record
    @hash = Gmaps4rails.build_markers(record) do |heir, marker|
        marker.lat heir.lan
        marker.lng heir.lng
        marker.infowindow heir.name
    end
  end

  def set_params
    @heir = Heir.new
  end

    def heir_params
      params.require(:heir).permit(:name.toLowerCase,:address,:dob,:dod,:member_id,:lan,:lng)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def searchhome
    data= params[:data]
    @products=Heir.where('name LIKE ?', "%#{data}%")
    gmap @products
    respond_to do |format|
      format.html
      format.js
   end
  end


  def dashboard
    data= params[:data]
    @products=Heir.where('name LIKE ?', "%#{data}%")
    gmap @products
    respond_to do |format|
      format.html
      format.js
   end
  end



  private

  def gmap record
    @hash = Gmaps4rails.build_markers(record) do |heir, marker|
        marker.lat heir.lan
        marker.lng heir.lng
        marker.infowindow heir.name
    end
  end


end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController
  before_action :authenticate_member!
#   def new
#     @member= Member.new
#     #@contact = Contact.new
#   end
#
#   def create
#
#     @member = Member.new(member_params)
#     @member.valid?
#     if @member.errors.blank?
#       @member.save
#       session[:mid]=@member.id
#       #@contact.member = @member
#       #@contact.save
#       redirect_to dashboard_path
#     else
#       render :action => "new"
#     end
#   end
#
#
# private
#
#   def member_params
#     params.require(:member).permit(:email,:password,:password_confirmation,:username,:address,:mobaile,:date_of_birth,:is_female,:provider,:uid)
#   end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/details/Edit.html.erb
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">

<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
  }
</style>
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<style>
  #locationField, #controls {
    position: relative;
    width: 480px;
  }
  #autocomplete {
    width: 50%;
  }
  .label {
    text-align: right;
    font-weight: bold;
    width: 100px;
    color: #303030;
  }
  #address {
    border: 1px solid #000090;
    background-color: #f0f0ff;
    width: 480px;
    padding-right: 2px;
  }
  #address td {
    font-size: 10pt;
  }
  .field {
    width: 99%;
  }
  .slimField {
    width: 80px;
  }
  .wideField {
    width: 200px;
  }
  #locationField {
    height: 20px;
    margin-bottom: 2px;
  }
</style>
<div id="locationField">

<h2>Edit Details</h2>

<%= form_for @heir, :url =>{:controller=>"details",:action => "Update",:id=>@heir} do |f| %>
<%= render 'error_messages', object: f.object %>

<div><%= f.label :name %><br/>
<%= f.text_field :name %></div>

    <div><%= f.label :address %><br/>
           <%= f.text_field :address, placeholder:'Enter Address',id:'autocomplete' %>
    </div>


<div><%= f.label :dob %><br />
 <%= f.date_select :dob %>
</div>

  <div><%= f.label :dob %><br />
   <%= f.date_select :dod %>
  </div>

  <%= f.hidden_field :lan %>
  <%= f.hidden_field :lng %>

</br>
<div><%= f.submit "Update" %></div>
<% end %>
</div>

<script>

  var placeSearch, autocomplete;

  function initAutocomplete() {
    // Create the autocomplete object, restricting the search to geographical
    // location types.
    autocomplete = new google.maps.places.Autocomplete(
        /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
        {types: ['geocode']});
    // When the user selects an address from the dropdown, populate the address
    // fields in the form.
    autocomplete.addListener('place_changed', fillInAddress);
  }
  function fillInAddress() {
    // Get the place details from the autocomplete object.
    var place = autocomplete.getPlace();

    $("#heir_lan").val(place.geometry.location.lat()); //val assign in
    $("#heir_lng").val(place.geometry.location.lng());
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATVd5qobu6xDAorZtWJD1UMIPelda_e9Q&libraries=places&callback=initAutocomplete"
    async defer>
</script>

app/views/details/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/details/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/details/_member.html.erb
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'sidebar_builder'}}, function(){

  markers = handler.addMarkers(<%=raw @hash.to_json %>);

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<br/>
<br/>

app/views/details/index.html.erb
<br/><br/>
<br/><br/>
<br/><br/>

<div class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <div class="section-title center">
          <h2><strong>Search</strong></h2>
          <div class="line">
            <hr>
          </div>
          <div class="clearfix">

          </div>
        </div>

        <div class="form-group">
          <%= search_form_for @search, url: search_details_path, method: :post do |f| %>
          <table>
            <tr>
              <td class="tdser">  <%= f.text_field :name_cont, :placeholder=>"Enter Name",:class=>"form-control" %><td>
                <td>&nbsp&nbsp&nbsp</td>
                <td>  <%= f.submit "Search",:class=>"btn tf-btn btn-default sbtnser" %> <td>
                </tr>
              </table>
              <% end %>

            </div>
            <br/>


          </div>
        </div>
        <div id="sidebar_builder" class="map"></div>
      </div>
    </div>
  </div>

  <br/><br/>


  <script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'sidebar_builder'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
  </script>

app/views/details/new.html.erb
</br></br></br></br></br></br>



<div class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <div class="section-title center">
          <h2><strong>Details</strong></h2>
          <div class="line">
            <hr>
          </div>
          <div class="clearfix"></div>
          <small><em></em></small>
        </div>

        <%= form_for @heir, :url =>{:controller=>"details",:action => "create"} do |f| %>
          <%= render 'error_messages', object: f.object %>


        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name,:class=>"form-control", :placeholder=>"Enter Name" %>

        </div>

        <div class="form-group">
          <table>
              <tr>
                <td><label>Address</label><%= f.hidden_field :address %></td>
              </tr>
          </table>
              <div id="sidebar_build" class="map"></div>
          <br/>


        <div class="form-group">
          <table>
              <tr>
                <td><label>Date of Birth</label></td>
              </tr>
              <tr>
                <td><%= f.date_select :dob,:start_year=>1980,:end_year=>2017 %></td>
              </tr>
          </table>
        </div>


        <div class="form-group">
          <table>
              <tr>
                <td><label>Date of Death</label></td>
              </tr>
              <tr>
                <td><%= f.date_select :dod,:start_year=>1980,:end_year=>2017 %></td>
              </tr>
          </table>
        </div>

        <%= f.hidden_field :member_id, :value => current_member.id %>
        <%= f.hidden_field :lan %>
        <%= f.hidden_field :lng %>


        <%= f.submit "Submit", :class=>"btn tf-btn btn-default sbtn"%>
        <% end %>
      </div>

    </div>
  </div>

</div>
</div>

<script>


</script>
<script async defer
 src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWtPc7P3WE-qisP-f-tSiGZJO__iD6Pw8&callback=initialize">
</script>


    <br/>  <br/>

app/views/details/searchajax.html.erb
<br><br>
<br><br>
<br><br>

<div class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <div class="section-title center">
          <h2><strong>Search</strong></h2>
            <div class="line">
              <hr>
            </div>
          <div class="clearfix">

          </div>
        </div>

        <div class="form-group">
           <%= text_field_tag :search, params[:search] , :placeholder=>"Enter Name",:class=>"form-control" %>
        </div>
        <br/>
      </div>
    </div>
    <div id="sidebar_builder" class="map"></div>
  </div>
</div>
</div>
<div id="memberlist"><%= render 'member'%></div>

app/views/details/searchajax.js.erb
 $('#memberlist').html('<%= escape_javascript(render("member")) %>');

app/views/home/_member.html.erb
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'sidebar_builder'}}, function(){

  markers = handler.addMarkers(<%=raw @hash.to_json %>);

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>
<br/>

app/views/home/about.html.erb
<!-- About Us Page
==========================================-->
  <br/><br/><br/>  <br/><br/><br/>
<div id="tf-about">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="/assets/02.png" class="img-responsive">
            </div>
            <div class="col-md-6">
                <div class="about-text">
                    <div class="section-title">
                        <h4>About us</h4>
                        <h2>Some words <strong>about us</strong></h2>
                        <hr>
                        <div class="clearfix"></div>
                    </div>
                    <p class="intro">We love building and rebuilding brands through our  specific skills. Using colour, fonts, and illustration, we brand companies in a way they will never forget.</p>
                    <ul class="about-list">
                        <li>
                            <span class="fa fa-dot-circle-o"></span>
                            <strong>Mission</strong> - <em>We deliver uniqueness and quality</em>
                        </li>
                        <li>
                            <span class="fa fa-dot-circle-o"></span>
                            <strong>Skills</strong> - <em>Delivering fast and excellent results</em>
                        </li>
                        <li>
                            <span class="fa fa-dot-circle-o"></span>
                            <strong>Clients</strong> - <em>Satisfied clients thanks to our experience</em>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/dashboard.html.erb
  </br></br></br>
  <% if member_signed_in?%>
    <div id="tf-contact" class="text-center">
      <div class="container">
          <div class="row">
              <div class="col-md-8 col-md-offset-2">

                  <div class="section-title center">
                      <h2>welcome <strong><%= current_member.username %>.</strong></h2>
                      <div class="line">
                          <hr>
                      </div>
                  </div>



                        <div class="col-md-8 col-md-offset-2">

                          <div>
                          </div>

                          <div class="form-group">
                             <%= text_field_tag :search, params[:search] , :placeholder=>"Enter Name",:class=>"form-control" %>
                          </div>
                          <br/>


                        </div>
                      </div>
                      <div id="sidebar_builder" class="map"></div>

                      <div id="memberlist"><%= render 'member'%></div>
              </div>
          </div>
  </div>
<%else%>
</br></br></br></br></br>
  <div id="tf-contact" class="text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="section-title center">
                    <h2>Please <strong><%= link_to "Login", new_member_session_path, :class => 'page-scroll'  %> into System.</strong></h2>
                    <div class="line">
                        <hr>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<% end %>

app/views/home/dashboard.js.erb
 $('#memberlist').html('<%= escape_javascript(render("member")) %>');

app/views/home/index.html.erb
<!-- Home Page
==========================================-->



<div id="tf-home" class="text-center">
  <div class="overlay">
    <div class="content">
      <% if member_signed_in?%>
        <h1>Logged in as <strong><%= current_member.email %></strong>
        <br/><br/>Welcome on <strong><span class="color">Cemetery</span></strong></h1>
        <p class="lead">We are a digital agency with <strong>years of experience</strong> and with <strong>extraordinary people</strong></p>
        <!-- <a href="#tf-about" class="fa fa-angle-down page-scroll"></a> -->
        <%else%>
        <h1>Welcome on <strong><span class="color">Cemetery</span></strong></h1>
        <p class="lead">We are a digital agency with <strong>years of experience</strong> and with <strong>extraordinary people</strong></p>
        <br/>click hear for<strong><span class="color"><%= link_to " Search", searchhome_path, :class => 'page-scroll'  %></span></strong></h1>
        <%end%>
      </div>
    </div>
  </div>

app/views/home/searchhome.js.erb
 $('#memberlist').html('<%= escape_javascript(render("member")) %>');

app/views/layouts/_menu.html.erb
<!-- Navigation
==========================================-->
<nav id="tf-menun" class="navbar navbar-default navbar-fixed-top manubar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if member_signed_in? %>
        <%= link_to "CEMETERY", dashboard_path,:class =>"navbar-brand wh" %>
      <% else %>
        <%= link_to "CEMETERY", root_path,:class =>"navbar-brand wh" %>
      <% end%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

  <!-- <li><a href="#"><i class="fa fa-home"></i></a></li> -->
        <% if member_signed_in? %>
          <!-- <li>Logged in as <strong><%= current_member.email %></strong></li> -->

          <li><%= link_to dashboard_path, :class => 'page-scroll' do %><i class="fa fa-home"></i> <% end -%></li>
          <li><%= link_to 'Add New Data',cemetoryform_path, :class => 'page-scroll','data-no-turbolink' => true %> </li>
          <li><%= link_to 'View List',list_path, :class => 'page-scroll' %></li>
          <li><%= link_to "Search", indexsearch_path, :class => 'page-scroll'  %> </li>
          <!-- <li><%= link_to "Real Time Search", searchajax_path, :class => 'page-scroll'  %></li> -->
          <li><%= link_to 'Edit profile', edit_member_registration_path, :class => 'page-scroll' %></li>
          <li><%= link_to "Logout", destroy_member_session_path, method: :delete, :class => 'page-scroll'%></li>
        <% else %>
          <!-- <li><%= link_to "Home", root_path,:class =>"page-scroll" %><li> -->
          <li><%= link_to "Search", searchhome_path, :class => 'page-scroll'  %></li>
          <li><%= link_to "About us", about_path,:class =>"page-scroll" %><li>
          <li><%= link_to "Contact us", contact_path,:class =>"page-scroll" %><li>

        <li><%= link_to "Sign up", new_member_registration_path, :class => 'page-scroll'  %> </li>
        <li><%= link_to "Login", new_member_session_path, :class => 'page-scroll'  %></li>
        <% end %>

         <%#= link_to 'Sign In with Github', "https://github.com/login/oauth/authorize?client_id=e88c005e5227b6f40960"  %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://maps.google.com/maps/api/js?key=AIzaSyDWtPc7P3WE-qisP-f-tSiGZJO__iD6Pw8"></script>
    <script src="https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <title>Cemetery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'bootstrap' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->


  </head>

  <body>

    <%= render '/layouts/menu'%>

      <!-- <% if member_signed_in? %>
        Logged in as <strong><%= current_member.email %></strong>. |
        <%= link_to "Search", indexsearch_path, :class => 'navbar-link'  %> |
        <%= link_to "Search_Ajax", searchajax_path, :class => 'navbar-link'  %>
        |
        <%= link_to 'Home',dashboard_path, :class => 'navbar-link' %> |
        <%= link_to 'Add New Data',cemetoryform_path, :class => 'navbar-link' %> |
        <%= link_to 'View List',list_path, :class => 'navbar-link' %>
         |
        <%= link_to 'Edit profile', edit_member_registration_path, :class => 'navbar-link' %> |

        <%= link_to "Logout", destroy_member_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>


        <%= link_to "Sign up", new_member_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_member_session_path, :class => 'navbar-link'  %>
      <% end %> -->

       <%#= link_to 'Sign In with Github', "https://github.com/login/oauth/authorize?client_id=e88c005e5227b6f40960"  %>

  <%= yield %>
   <%= render '/layouts/footer' %>

   </body>
</html>

app/views/members/shared/_links.html.erb
<script>
window.fbAsyncInit = function() {
  FB.init({
    appId      : '284213748660868',
    cookie     : true,
    xfbml      : true,
    version    : 'v2.8'
  });
  FB.AppEvents.logPageView();
};

(function(d, s, id){
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

FB.getLoginStatus(function(response) {
  statusChangeCallback(response);
});


</script>
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
<div>
    <%= link_to omniauth_authorize_path(resource_name, 'github'), class: "btn btn-social btn-github" do %>
       <span class="fa fa-github"></span> Sign in with Github
    <% end -%>
</div>
<div>

        <%= link_to omniauth_authorize_path(resource_name, 'facebook'), class: "btn btn-social btn-facebook" do %>
           <span class="fa fa-facebook"></span> Sign in with facebook
        <% end -%>
</div>
  <!-- <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%> -->
<% end -%>



<!-- <div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="true" data-auto-logout-link="true"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8&appId=284213748660868";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> -->